# Generated by Django 2.1.7 on 2019-09-30 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190930_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='questionid',
            new_name='question',
        ),
    ]
