# Generated by Django 2.1.7 on 2019-10-11 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190930_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panswers',
            old_name='answer',
            new_name='panswer',
        ),
        migrations.AddField(
            model_name='panswers',
            name='pquestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.POquestions'),
        ),
    ]
