# Generated by Django 2.1.7 on 2019-10-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191011_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='panswers',
            name='panswer',
            field=models.CharField(max_length=1),
        ),
    ]
