# Generated by Django 2.1.7 on 2019-10-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20191011_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panswers',
            name='panswer',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=6),
        ),
        migrations.AlterField(
            model_name='poquestions',
            name='pquestion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=200),
        ),
    ]
