# Generated by Django 2.2.5 on 2019-09-25 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190923_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='questionid',
            new_name='question',
        ),
    ]
