# Generated by Django 2.2.5 on 2019-09-25 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190925_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='questionid',
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.questions'),
        ),
    ]
