# Generated by Django 2.1.7 on 2019-08-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subid',
            field=models.IntegerField(),
        ),
    ]
